# -*- coding: utf-8 -*-
"""
predict_lr_with_evidence_all.py

Purpose:
- On the 'all' dataset, use your current
  "TF-IDF(text) + numeric features + LogisticRegression" model for prediction
- At the same time, attach one REAL evidence sample to each example
  (using retrieval results generated by build_evidence_pairs_all.py)
- Output a CSV to conveniently show “input + prediction + evidence” in reports / demos

Example usage (inside .venv_torch):
    python src/predict_lr_with_evidence_all.py --split val
    python src/predict_lr_with_evidence_all.py --split test
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, classification_report
from sklearn.pipeline import Pipeline

from config import FEATURES_DIR, OUT_DIR

# Directory where evidence files are stored (generated by build_evidence_pairs_all.py)
EVIDENCE_DIR = OUT_DIR / "evidence" / "all"

# Directory to store prediction outputs
PRED_DIR = OUT_DIR / "predictions"
PRED_DIR.mkdir(parents=True, exist_ok=True)


def build_lr_pipeline(numeric_features):
    """
    Build an LR pipeline with the same configuration as baseline_lr_plus_feats.py:
    - TF-IDF(text) + numeric features + LogisticRegression
    """
    preprocess = ColumnTransformer(
        transformers=[
            (
                "text",
                TfidfVectorizer(
                    max_features=50000,
                    ngram_range=(1, 2),
                    min_df=5,
                    max_df=0.9,
                    sublinear_tf=True,
                ),
                "clean_text",
            ),
            ("num", "passthrough", numeric_features),
        ],
        remainder="drop",
    )

    model = Pipeline(
        steps=[
            ("preprocess", preprocess),
            (
                "logreg",
                LogisticRegression(
                    max_iter=500,  # Slightly larger than 200 to ensure convergence
                    n_jobs=-1,
                    class_weight=None,
                ),
            ),
        ]
    )
    return model


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--split",
        type=str,
        default="val",
        choices=["train", "val", "test"],
        help="Which split to predict on (train/val/test). Default: val",
    )
    args = parser.parse_args()

    dataset = "all"
    in_dir = FEATURES_DIR / dataset

    train_path = in_dir / "train_fe.csv"
    split_path = in_dir / f"{args.split}_fe.csv"

    print("LR features train path:", train_path)
    print("LR features split path:", split_path)

    train_df = pd.read_csv(train_path)
    split_df = pd.read_csv(split_path)

    print("Train shape:", train_df.shape)
    print(f"{args.split} shape:", split_df.shape)

    # y
    y_train = train_df["label"].astype(int).values
    y_true = split_df["label"].astype(int).values

    # X: drop label / label_text columns, use all remaining columns as input
    drop_cols = [c for c in ["label", "label_text"] if c in train_df.columns]
    X_train = train_df.drop(columns=drop_cols)
    X_split = split_df.drop(columns=drop_cols)

    # Numeric feature columns (keep consistent with baseline_lr_plus_feats.py)
    numeric_features = [
        "num_chars",
        "num_words",
        "avg_word_len",
        "num_exclamation",
        "num_question",
        "unique_words",
        "lexical_richness",
        "num_stopwords",
        "stopword_ratio",
        "num_digits",
        "digit_ratio",
        "num_urls",
        "year",
        "month",
    ]

    # In case some columns are missing
    for col in numeric_features:
        if col not in X_train.columns:
            X_train[col] = 0
        if col not in X_split.columns:
            X_split[col] = 0

    X_train[numeric_features] = X_train[numeric_features].fillna(0)
    X_split[numeric_features] = X_split[numeric_features].fillna(0)

    # Build and train LR model
    model = build_lr_pipeline(numeric_features)

    print("\n[LR] Fitting TF-IDF(text) + numeric features + LogisticRegression on 'all' train...")
    model.fit(X_train, y_train)

    print(f"[LR] Predicting on '{args.split}' split...")
    y_pred = model.predict(X_split)
    probas = model.predict_proba(X_split)[:, 1]  # P(FAKE)

    acc = accuracy_score(y_true, y_pred)
    macro_f1 = f1_score(y_true, y_pred, average="macro")

    print(f"\n=== LR+features on 'all' / {args.split} ===")
    print("Accuracy :", acc)
    print("Macro F1 :", macro_f1)
    print("\nClassification report:")
    print(
        classification_report(
            y_true, y_pred, target_names=["REAL (0)", "FAKE (1)"]
        )
    )

    # -------------------------------
    # Read evidence, align by rows, and merge for output
    # -------------------------------
    evidence_path = EVIDENCE_DIR / f"all_pairs_{args.split}.csv"
    print(f"\n[Evidence] Reading {args.split} evidence from {evidence_path}")
    evi_df = pd.read_csv(evidence_path)

    if len(evi_df) != len(split_df):
        raise ValueError(
            f"Evidence rows ({len(evi_df)}) != split rows ({len(split_df)}). "
            f"Please ensure build_evidence_pairs_all.py was run on the same all/{args.split}.csv."
        )

    # Label mapping
    label_map = {0: "REAL", 1: "FAKE"}

    # Build the output table: each row is input + prediction + evidence
    out_df = pd.DataFrame()

    # Keep some original info if available
    for col in ["id", "title", "source_dataset"]:
        if col in split_df.columns:
            out_df[col] = split_df[col]

    out_df["clean_text"] = split_df["clean_text"]
    out_df["true_label"] = y_true
    out_df["true_label_text"] = [label_map[int(y)] for y in y_true]

    out_df["pred_label"] = y_pred
    out_df["pred_label_text"] = [label_map[int(y)] for y in y_pred]
    out_df["pred_proba_fake"] = probas

    # Take evidence_text and similarity from evidence table
    out_df["evidence_text"] = evi_df["evidence_text"]
    out_df["evidence_sim"] = evi_df["evidence_sim"]

    # Optionally, we could keep the id/title of the REAL sample from which the
    # evidence comes (if such columns exist).
    # Here evi_df is basically some columns from the original all/{split}.csv + evidence_text,
    # but our retrieval corpus is train-REAL, so we may not have a straightforward evidence_id.
    # To keep it simple, we skip that for now.

    out_path = PRED_DIR / f"all_lr_with_evidence_{args.split}.csv"
    out_df.to_csv(out_path, index=False, encoding="utf-8")

    print(f"\n[done] Saved predictions with evidence to: {out_path}")


if __name__ == "__main__":
    main()
